using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;

namespace Website
{
    public class Global : System.Web.HttpApplication
    {
        protected void Application_Start(object sender, EventArgs e)
        {
            Application["productsList"] = new List<ProductsList>();
            List<ProductsList> productsList = new List<ProductsList>();
            Application["user"] = new List<User>();
            //CHO
            //Nike
            productsList.Add(new ProductsList() { id = "1.1", img = "./Images/Nike/cho1.png", name = "Bánh cho chó vị thịt bò", price = "2649000", detail_heading = "An toàn cho thú cưng của bạn.", type = "dog",});
            //productsList.Add(new ProductsList() { id = "1.2", img = "./Images/Nike/Nike_1-Black.svg", name = "Nike Air Force 1 '07", price = "2649000", detail_heading = "Phong cách huyền thoại.", detail = "Sự rạng rỡ tồn tại trong Nike Air Force 1 '07 mang đến một sự thay đổi mới mẻ về những gì bạn biết rõ nhất: các lớp phủ được khâu đẹp, kết thúc sạch sẽ và lượng đèn flash hoàn hảo để khiến bạn tỏa sáng.", type = "nike", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "1.3", img = "./Images/Nike/Nike_1-Red.svg", name = "Nike Air Force 1 '07", price = "2649000", detail_heading = "Phong cách huyền thoại.", detail = "Sự rạng rỡ tồn tại trong Nike Air Force 1 '07 mang đến một sự thay đổi mới mẻ về những gì bạn biết rõ nhất: các lớp phủ được khâu đẹp, kết thúc sạch sẽ và lượng đèn flash hoàn hảo để khiến bạn tỏa sáng.", type = "nike", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "2.1", img = "./Images/Nike/cho2.png", name = "Thức ăn cho chó trưởng thành", price = "2929000", detail_heading = "An toàn cho thú cưng của bạn.",  type="dog"});
            //productsList.Add(new ProductsList() { id = "2.2", img = "./Images/Nike/Nike_2-Black.svg", name = "Nike Blazer Mid '77 Vintage", price = "2929000", detail_heading = "Phong cách cổ điển.", detail = "Vào những năm 70, Nike là hãng giày mới. Nên trên thực tế, chúng tôi vẫn đang thâm nhập thị trường bóng rổ và thử nghiệm các nguyên mẫu trên chân đội địa phương của chúng tôi. Tất nhiên, thiết kế được cải thiện trong những năm qua, nhưng cái tên vẫn như cũ. Nike Blazer Mid '77 Vintage - cổ điển ngay từ đầu.", type = "nike", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "2.3", img = "./Images/Nike/Nike_2-Red.svg", name = "Nike Blazer Mid '77 Vintage", price = "2929000", detail_heading = "Phong cách cổ điển.", detail = "Vào những năm 70, Nike là hãng giày mới. Nên trên thực tế, chúng tôi vẫn đang thâm nhập thị trường bóng rổ và thử nghiệm các nguyên mẫu trên chân đội địa phương của chúng tôi. Tất nhiên, thiết kế được cải thiện trong những năm qua, nhưng cái tên vẫn như cũ. Nike Blazer Mid '77 Vintage - cổ điển ngay từ đầu.", type = "nike", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "3.1", img = "./Images/Nike/cho3.png", name = "Sữa tắm cho chó lông màu", price = "2929000", detail_heading = "An toàn cho thú cưng của bạn.", type = "dog" });
            //productsList.Add(new ProductsList() { id = "3.2", img = "./Images/Nike/Nike_3-Black.svg", name = "Nike Air Force 1 '07 LV8", price = "2929000", detail_heading = "Một sneaker huyền thoại cho ngày kỷ niệm thế giới", detail = "Nike Air Force 1 '07 LV8 cập nhật mẫu '82 OG lấy cảm hứng từ vòng đệm với chi tiết lấy cảm hứng từ Trái đất để có kiểu dáng đẹp nhằm tôn vinh Ngày Thế giới tử tế.", type = "nike", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "3.3", img = "./Images/Nike/Nike_3-Red.svg", name = "Nike Air Force 1 '07 LV8", price = "2929000", detail_heading = "Một sneaker huyền thoại cho ngày kỷ niệm thế giới", detail = "Nike Air Force 1 '07 LV8 cập nhật mẫu '82 OG lấy cảm hứng từ vòng đệm với chi tiết lấy cảm hứng từ Trái đất để có kiểu dáng đẹp nhằm tôn vinh Ngày Thế giới tử tế.", type = "nike", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "4.1", img = "./Images/Nike/cho4.png", name = "Dầu xả cho chó làm sáng lông", price = "3519000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "dog"});
            //productsList.Add(new ProductsList() { id = "4.2", img = "./Images/Nike/Nike_4-Black.svg", name = "Nike Air Zoom SuperRep 2", price = "3519000", detail_heading = "Đệm sáng tạo - Thoải mái hơn bao giờ", detail = "Nike Air Zoom SuperRep 2 được thiết kế để luyện tập theo mạch, HIIT, chạy nước rút và các bài tập tốc độ nhanh khác. Các lớp hỗ trợ kết hợp với đệm Zoom Air để giữ cho bàn chân của bạn được khóa chặt và thoải mái khi bạn lao xuống, nhảy và đẩy theo cách của bạn qua mỗi lần thực hiện. Thiết kế rộng rãi hơn xung quanh các ngón chân giúp bạn có được sự vừa vặn hoàn hảo.", type = "nike", color = "Đen" });
            productsList.Add(new ProductsList() { id = "5.1", img = "./Images/Nike/cho5.png", name = "Sữa bột cho chó", price = "4699000", detail_heading = "An toàn cho thú cưng của bạn.", type = "dog" });
            //productsList.Add(new ProductsList() { id = "5.2", img = "./Images/Nike/Nike_5-Black.svg", name = "Air Jordan 1 Hi FlyEase", price = "4699000", detail_heading = "Đi vào chuyến bay.", detail = "Air Jordan 1 Hi FlyEase mang đến cho bạn một cách nhanh chóng và dễ dàng để đi vào đôi giày thể thao của mình trong khi vẫn duy trì sức hấp dẫn vượt thời gian của bản gốc. Cổ giày được kéo ra và các nếp gấp trên cùng mở ra để tạo ra một lối vào rộng, làm cho một trong những đôi giày mang tính biểu tượng nhất mọi thời đại trở nên dễ dàng hơn bao giờ hết.", type = "nike", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "5.3", img = "./Images/Nike/Nike_5-Red.svg", name = "Air Jordan 1 Hi FlyEase", price = "4699000", detail_heading = "Đi vào chuyến bay.", detail = "Air Jordan 1 Hi FlyEase mang đến cho bạn một cách nhanh chóng và dễ dàng để đi vào đôi giày thể thao của mình trong khi vẫn duy trì sức hấp dẫn vượt thời gian của bản gốc. Cổ giày được kéo ra và các nếp gấp trên cùng mở ra để tạo ra một lối vào rộng, làm cho một trong những đôi giày mang tính biểu tượng nhất mọi thời đại trở nên dễ dàng hơn bao giờ hết.", type = "nike", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "6.1", img = "./Images/Nike/cho6.png", name = "Sữa tắm cho chó con", price = "3100000", detail_heading = "An toàn cho thú cưng của bạn.", type = "dog"});
            //productsList.Add(new ProductsList() { id = "6.2", img = "./Images/Nike/Nike_6-Black.svg", name = "Jordan Max 200 'Bayou Boys'", price = "3100000", detail_heading = "Big air, bayou vibe đậm.", detail = "Với các yếu tố lấy cảm hứng từ Air Jordans trong quá khứ, Jordan Max 200 'Bayou Boys' mang đến sự kết hợp giữa quá khứ và hiện đại, đệm và thiết kế lấy cảm hứng từ công nghệ. Phiên bản 'Bayou Boys' đặc biệt này sử dụng màu sắc và các chi tiết lấy cảm hứng từ da cá sấu thể hiện bang Louisiana, quê hương mới của Zion.", type = "nike", color = "Đen" });
            productsList.Add(new ProductsList() { id = "7.1", img = "./Images/Nike/cho7.png", name = "Thức ăn cho chó BOWWOW", price = "2039000", detail_heading = "An toàn cho thú cưng của bạn.", type = "dog"});
            //productsList.Add(new ProductsList() { id = "7.2", img = "./Images/Nike/Nike_7-Black.svg", name = "Air Jordan 3 Retro SE", price = "2039000", detail_heading = "Iconic instinct.", detail = "Sự hoang dã trong Air Jordan 3 Retro SE là một phần của gói 'Instinct', nó có sự kết hợp của các vật liệu lấy cảm hứng từ động vật mang lại bản sắc mới mẻ cho đôi giày mang tính biểu tượng.", type = "nike", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "7.3", img = "./Images/Nike/Nike_7-Red.svg", name = "Air Jordan 3 Retro SE", price = "2039000", detail_heading = "Iconic instinct.", detail = "Sự hoang dã trong Air Jordan 3 Retro SE là một phần của gói 'Instinct', nó có sự kết hợp của các vật liệu lấy cảm hứng từ động vật mang lại bản sắc mới mẻ cho đôi giày mang tính biểu tượng.", type = "nike", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "8.1", img = "./Images/Nike/cho8.png", name = "Xương cho chó gặm làm sạch răng", price = "5983000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "dog" });
            

            ////Adidas
            productsList.Add(new ProductsList() { id = "21.1", img = "./Images/Adidas/meo1.png", name = "Bánh cho mèo vị cá", price = "2400000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat"});
            //productsList.Add(new ProductsList() { id = "21.2", img = "./Images/Adidas/Adidas_1-Black.svg", name = "Sneaker Superstar", price = "2400000", detail_heading = "Thiết kế cổ thấp đặc trưng với mũi giày vỏ sò.", detail = "Thiết kế ban đầu dành cho sân bóng rổ vào thập niên 70. Được các ngôi sao hip hop tôn sùng vào thập niên 80. Đôi giày adidas Superstar giờ đây đã trở thành biểu tượng của các tín đồ thời trang đường phố. Thiết kế mũi giày vỏ sò nổi tiếng thế giới mang đến phong cách chất lừ và khả năng bảo vệ. Giống như những gì đôi giày này đã thể hiện trên sân bóng rổ trong quá khứ. Giờ đây, bạn có thể tự tin tham gia lễ hội âm nhạc hay dạo phố mà không sợ bị dẫm lên chân. Chi tiết 3 Sọc viền răng cưa và logo adidas Superstar đóng khung mang đậm phong cách nguyên bản chính hiệu.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "21.3", img = "./Images/Adidas/Adidas_1-Red.svg", name = "Sneaker Superstar", price = "2400000", detail_heading = "Thiết kế cổ thấp đặc trưng với mũi giày vỏ sò.", detail = "Thiết kế ban đầu dành cho sân bóng rổ vào thập niên 70. Được các ngôi sao hip hop tôn sùng vào thập niên 80. Đôi giày adidas Superstar giờ đây đã trở thành biểu tượng của các tín đồ thời trang đường phố. Thiết kế mũi giày vỏ sò nổi tiếng thế giới mang đến phong cách chất lừ và khả năng bảo vệ. Giống như những gì đôi giày này đã thể hiện trên sân bóng rổ trong quá khứ. Giờ đây, bạn có thể tự tin tham gia lễ hội âm nhạc hay dạo phố mà không sợ bị dẫm lên chân. Chi tiết 3 Sọc viền răng cưa và logo adidas Superstar đóng khung mang đậm phong cách nguyên bản chính hiệu.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "22.1", img = "./Images/Adidas/meo2.png", name = "Sữa tắm cho mèo hương hoa violet", price = "3100000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat" });
            //productsList.Add(new ProductsList() { id = "22.2", img = "./Images/Adidas/Adidas_2-Black.svg", name = "OZWEEGO", price = "3100000", detail_heading = "Đôi giày khởi đầu vào thập niên 90.", detail = "Cải biên, rồi lại cải tiến. Ra đời vào thập niên 1990, đôi giày chạy bộ OZWEEGO 3 nổi tiếng với thiết kế thoải mái nhẹ nhàng và phong cách thập niên 90. Đôi giày adidas này chắt lọc những nét tinh túy nhất của phong cách hoài cổ ấy và biến tấu thành một phiên bản hoàn toàn mới. Các chi tiết dạng ống trên gót giày mang đến phong cách hoài cổ lai công nghệ đúng chất.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "22.3", img = "./Images/Adidas/Adidas_2-Red.svg", name = "OZWEEGO", price = "3100000", detail_heading = "Đôi giày khởi đầu vào thập niên 90.", detail = "Cải biên, rồi lại cải tiến. Ra đời vào thập niên 1990, đôi giày chạy bộ OZWEEGO 3 nổi tiếng với thiết kế thoải mái nhẹ nhàng và phong cách thập niên 90. Đôi giày adidas này chắt lọc những nét tinh túy nhất của phong cách hoài cổ ấy và biến tấu thành một phiên bản hoàn toàn mới. Các chi tiết dạng ống trên gót giày mang đến phong cách hoài cổ lai công nghệ đúng chất.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "23.1", img = "./Images/Adidas/meo3.png", name = "Sữa tắm cho mèo hương hoa quýt", price = "5000000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat"});
            //productsList.Add(new ProductsList() { id = "23.2", img = "./Images/Adidas/Adidas_3-Black.svg", name = "ULTRABOOST 21", price = "5000000", detail_heading = "Năng lượng chỉ là năng lượng cho đến khi vào tay Ultraboost 21.", detail = "Hàng loạt bản mẫu. Hàng loạt cải tiến. Hàng loạt thử nghiệm. Đồng hành cùng chúng tôi trên hành trình tìm kiếm sự hòa hợp đỉnh cao giữa trọng lượng, sự êm ái và độ đàn hồi. Ultraboost 21. Đón chào nguồn năng lượng hoàn trả phi thường.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "23.3", img = "./Images/Adidas/Adidas_3-Red.svg", name = "ULTRABOOST 21", price = "5000000", detail_heading = "Năng lượng chỉ là năng lượng cho đến khi vào tay Ultraboost 21.", detail = "Hàng loạt bản mẫu. Hàng loạt cải tiến. Hàng loạt thử nghiệm. Đồng hành cùng chúng tôi trên hành trình tìm kiếm sự hòa hợp đỉnh cao giữa trọng lượng, sự êm ái và độ đàn hồi. Ultraboost 21. Đón chào nguồn năng lượng hoàn trả phi thường.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "24.1", img = "./Images/Adidas/meo4.png", name = "Thức ăn cho mèo trưởng thành", price = "2100000", detail_heading = "An toàn cho thú cưng của bạn.",type = "cat" });
            //productsList.Add(new ProductsList() { id = "24.2", img = "./Images/Adidas/Adidas_4-Black.svg", name = "Response Super", price = "2100000", detail_heading = "Giày chạy bộ nâng đỡ giúp bạn chinh phục mục tiêu.", detail = "Xét cho cùng, thêm 20 giây có là gì? Vượt qua giới hạn của ngày hôm qua với đôi giày chạy bộ adidas này. Nhẹ lướt như bay trên từng sải bước với lớp đệm hoàn trả năng lượng. Xỏ giày và ra khỏi cửa chính là bước đi đúng đắn.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "24.3", img = "./Images/Adidas/Adidas_4-Red.svg", name = "Response Super", price = "2100000", detail_heading = "Giày chạy bộ nâng đỡ giúp bạn chinh phục mục tiêu.", detail = "Xét cho cùng, thêm 20 giây có là gì? Vượt qua giới hạn của ngày hôm qua với đôi giày chạy bộ adidas này. Nhẹ lướt như bay trên từng sải bước với lớp đệm hoàn trả năng lượng. Xỏ giày và ra khỏi cửa chính là bước đi đúng đắn.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "25.1", img = "./Images/Adidas/meo5.png", name = "Bánh cho mèo vị cua", price = "500000", detail_heading = "An toàn cho thú cưng của bạn.", type = "cat"});
            //productsList.Add(new ProductsList() { id = "25.2", img = "./Images/Adidas/Adidas_5-Black.svg", name = "RUNFALCON 2.0", price = "500000", detail_heading = "Đôi giày chạy bộ siêu nhẹ vừa nâng đỡ lại vừa phong cách.", detail = "Bạn đã chán tập gym và muốn thử chạy bộ? Đôi giày adidas này là lựa chọn hoàn hảo cho những người mới bắt đầu và muốn có được bệ phóng phù hợp. Thân giày bằng vải dệt siêu thoáng khí. Đế ngoài bằng cao su siêu bám trên các bề mặt ẩm ướt. Kết cấu siêu nhẹ giúp đôi chân bạn dễ dàng chuyển động.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "25.3", img = "./Images/Adidas/Adidas_5-Red.svg", name = "RUNFALCON 2.0", price = "500000", detail_heading = "Đôi giày chạy bộ siêu nhẹ vừa nâng đỡ lại vừa phong cách.", detail = "Bạn đã chán tập gym và muốn thử chạy bộ? Đôi giày adidas này là lựa chọn hoàn hảo cho những người mới bắt đầu và muốn có được bệ phóng phù hợp. Thân giày bằng vải dệt siêu thoáng khí. Đế ngoài bằng cao su siêu bám trên các bề mặt ẩm ướt. Kết cấu siêu nhẹ giúp đôi chân bạn dễ dàng chuyển động.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "26.1", img = "./Images/Adidas/meo6.png", name = "Bánh cho mèo vị cá", price = "2500000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat"});
            //productsList.Add(new ProductsList() { id = "26.2", img = "./Images/Adidas/Adidas_6-Black.svg", name = "Continental 80", price = "2500000", detail_heading = "Giày sneaker phong cách cổ điển với thiết kế 3 sọc đầy ấn tượng.", detail = "Tinh hoa phong cách fitness. Mang nét cổ điển đến cho phong cách hàng ngày của bạn với đôi giày adidas Continental 80 này. Ban đầu ra mắt vào cuối thập niên 80 là đôi sneaker đa năng dành cho tập luyện, phiên bản này thổi luồng gió mới vào một biểu tượng. Mượn cảm hứng từ bộ track suit cổ điển, biểu tượng 3 Sọc táo bạo chạy dọc thân giày.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "26.3", img = "./Images/Adidas/Adidas_6-Red.svg", name = "Continental 80", price = "2500000", detail_heading = "Giày sneaker phong cách cổ điển với thiết kế 3 sọc đầy ấn tượng.", detail = "Tinh hoa phong cách fitness. Mang nét cổ điển đến cho phong cách hàng ngày của bạn với đôi giày adidas Continental 80 này. Ban đầu ra mắt vào cuối thập niên 80 là đôi sneaker đa năng dành cho tập luyện, phiên bản này thổi luồng gió mới vào một biểu tượng. Mượn cảm hứng từ bộ track suit cổ điển, biểu tượng 3 Sọc táo bạo chạy dọc thân giày.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "27.1", img = "./Images/Adidas/meo7.png", name = "Súp cho mèo vị cá bào Nhật", price = "5000000", detail_heading = "An toàn cho thú cưng của bạn.", type = "cat" });
            //productsList.Add(new ProductsList() { id = "27.2", img = "./Images/Adidas/Adidas_7-Black.svg", name = "ULTRABOOST 20", price = "5000000", detail_heading = "Giày chạy bộ linh hoạt sử dụng sợi Parley Ocean Plastic.", detail = "Bạn chạy bộ vì sức khỏe bản thân. Vì bạn thích không gian ngoài trời. Đôi giày chạy bộ adidas này thể hiện niềm đam mê của bạn. Thân giày mềm mại, linh hoạt có sử dụng chất liệu nhựa thu gom từ các bờ biển và vùng ven biển. Đây là nỗ lực của adidas hướng tới chấm dứt rác thải nhựa. Và cũng là cách tuyệt vời cho thấy bạn quan tâm.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "27.3", img = "./Images/Adidas/Adidas_7-Red.svg", name = "ULTRABOOST 20", price = "5000000", detail_heading = "Giày chạy bộ linh hoạt sử dụng sợi Parley Ocean Plastic.", detail = "Bạn chạy bộ vì sức khỏe bản thân. Vì bạn thích không gian ngoài trời. Đôi giày chạy bộ adidas này thể hiện niềm đam mê của bạn. Thân giày mềm mại, linh hoạt có sử dụng chất liệu nhựa thu gom từ các bờ biển và vùng ven biển. Đây là nỗ lực của adidas hướng tới chấm dứt rác thải nhựa. Và cũng là cách tuyệt vời cho thấy bạn quan tâm.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "28.1", img = "./Images/Adidas/meo8.png", name = "Thức ăn cho mèo MININO", price = "990000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat" });
            //productsList.Add(new ProductsList() { id = "28.2", img = "./Images/Adidas/Adidas_8-Black.svg", name = "BRAVADA", price = "990000", detail_heading = "Giày vải Canvas mang đậm phong cách trượt ván.", detail = "Oanh tạc ngày mới với lớp đệm siêu êm ái. Thân giày bằng vải canvas và đế ngoài bằng cao su lưu hóa mang đến cho đôi giày adidas này vẻ ngoài mang đậm phong cách trượt ván. Lót giày có đệm cho cảm giác thoải mái dễ chịu khi bạn ra quán nhâm nhi tách cà phê hay đi bộ tới cửa hàng tạp hóa.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "28.3", img = "./Images/Adidas/Adidas_8-Red.svg", name = "BRAVADA", price = "990000", detail_heading = "Giày vải Canvas mang đậm phong cách trượt ván.", detail = "Oanh tạc ngày mới với lớp đệm siêu êm ái. Thân giày bằng vải canvas và đế ngoài bằng cao su lưu hóa mang đến cho đôi giày adidas này vẻ ngoài mang đậm phong cách trượt ván. Lót giày có đệm cho cảm giác thoải mái dễ chịu khi bạn ra quán nhâm nhi tách cà phê hay đi bộ tới cửa hàng tạp hóa.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "29.1", img = "./Images/Adidas/meo9.png", name = "Thức ăn cho mèo mọi lứa tuổi", price = "1800000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat" });
            //productsList.Add(new ProductsList() { id = "29.2", img = "./Images/Adidas/Adidas_9-Black.svg", name = "Grand Court", price = "1800000", detail_heading = "Đôi giày mang phong cách đậm chất adidas cổ điển.", detail = "Cuối tuần vẫy gọi. Đôi giày adidas này tôn lên nét gọn gàng và kinh điển. Phối cùng chiếc quần thể thao thường ngày, hoặc tạo nét tương phản với trang phục đường phố ưa thích của bạn. Bất kể lựa chọn của bạn là gì, đôi giày này sẽ nâng niu từng bước chân và giúp bạn tự tin sải bước.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "29.3", img = "./Images/Adidas/Adidas_9-Red.svg", name = "Grand Court", price = "1800000", detail_heading = "Đôi giày mang phong cách đậm chất adidas cổ điển.", detail = "Cuối tuần vẫy gọi. Đôi giày adidas này tôn lên nét gọn gàng và kinh điển. Phối cùng chiếc quần thể thao thường ngày, hoặc tạo nét tương phản với trang phục đường phố ưa thích của bạn. Bất kể lựa chọn của bạn là gì, đôi giày này sẽ nâng niu từng bước chân và giúp bạn tự tin sải bước.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "30.1", img = "./Images/Adidas/meo10.png", name = "Thức ăn cho mèo trên 7kg", price = "4500000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "cat" });
            //productsList.Add(new ProductsList() { id = "30.2", img = "./Images/Adidas/Adidas_10-Black.svg", name = "PREDATOR MUTATOR 20.1 FG", price = "4500000", detail_heading = "Giày bóng đá cổ lửng cho khả năng kiểm soát vượt trội trên sân cỏ tự nhiên.", detail = "Bạn không hề chơi ăn gian. Bạn chỉ đang lách luật. Tìm kiếm lợi thế và thay đổi cục diện trận đấu với đôi giày adidas Predator hoàn toàn mới. Thân giày bằng vải dệt kim ôm vừa vặn 360 độ quanh bàn chân, cùng thiết kế cổ lửng nâng đỡ vùng cổ chân. Gai cao su bám bóng tạo độ xoáy vượt trội, cùng đế ngoài phân tách giúp bạn chiếm ưu thế. Làm chủ thế trận với đôi giày bóng đá Predator Mutator 20.1 Firm Ground.", type = "adidas", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "30.3", img = "./Images/Adidas/Adidas_10-Red.svg", name = "PREDATOR MUTATOR 20.1 FG", price = "4500000", detail_heading = "Giày bóng đá cổ lửng cho khả năng kiểm soát vượt trội trên sân cỏ tự nhiên.", detail = "Bạn không hề chơi ăn gian. Bạn chỉ đang lách luật. Tìm kiếm lợi thế và thay đổi cục diện trận đấu với đôi giày adidas Predator hoàn toàn mới. Thân giày bằng vải dệt kim ôm vừa vặn 360 độ quanh bàn chân, cùng thiết kế cổ lửng nâng đỡ vùng cổ chân. Gai cao su bám bóng tạo độ xoáy vượt trội, cùng đế ngoài phân tách giúp bạn chiếm ưu thế. Làm chủ thế trận với đôi giày bóng đá Predator Mutator 20.1 Firm Ground.", type = "adidas", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "31.1", img = "./Images/Adidas/meo11.png", name = "Thức ăn khô cho mèo gói 500g", price = "1700000", detail_heading = "An toàn cho thú cưng của bạn.", type = "cat" });
            productsList.Add(new ProductsList() { id = "50.1", img = "./Images/Puma/chim1.png", name = "Thức ăn cho chim non loại 250g", price = "2000000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "diff"});
            //productsList.Add(new ProductsList() { id = "50.2", img = "./Images/Puma/Puma_10-Black.svg", name = "UltraRide Running Shoes", price = "2000000", detail_heading = "Vượt qua giới hạn của bản thân.", detail = "Được xây dựng dựa trên nền tảng của Lý thuyết Giảm thiểu, UltraRide loại bỏ các giới hạn với các đường cắt đế ngoài để mang lại cho bạn một điều cần thiết khi chạy cơ bản: đệm và khả năng đáp ứng cho tiềm năng vô hạn. Một tấm midsole nhẹ, thoáng mát và hỗ trợ kết hợp với nhau thông qua thiết kế cầu năng động. Được kết hợp với PROFOAMLITE để làm đệm và diện tích bề mặt cao su để truyền lực ngay từ đầu, UltraRide mang bạn đến những điều tuyệt vời. Nó hoàn toàn đơn giản.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "50.3", img = "./Images/Puma/Puma_10-Red.svg", name = "UltraRide Running Shoes", price = "2000000", detail_heading = "Vượt qua giới hạn của bản thân.", detail = "Được xây dựng dựa trên nền tảng của Lý thuyết Giảm thiểu, UltraRide loại bỏ các giới hạn với các đường cắt đế ngoài để mang lại cho bạn một điều cần thiết khi chạy cơ bản: đệm và khả năng đáp ứng cho tiềm năng vô hạn. Một tấm midsole nhẹ, thoáng mát và hỗ trợ kết hợp với nhau thông qua thiết kế cầu năng động. Được kết hợp với PROFOAMLITE để làm đệm và diện tích bề mặt cao su để truyền lực ngay từ đầu, UltraRide mang bạn đến những điều tuyệt vời. Nó hoàn toàn đơn giản.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "51.1", img = "./Images/Puma/chim2.png", name = "Thức ăn cho sóc KIGO loại 500g", price = "1990000", detail_heading = "An toàn cho thú cưng của bạn.", type = "diff"});
            //productsList.Add(new ProductsList() { id = "51.2", img = "./Images/Puma/Puma_11-Black.svg", name = "Ralph Sampson 70 Sneakers", price = "1990000", detail_heading = "Phiên bản nguyên mẫu", detail = "Quay trở lại năm 1983, khi huyền thoại bóng rổ Ralph Sampson lần đầu tiên ký hợp đồng với PUMA, anh ấy đã chơi một đôi giày nguyên mẫu dựa trên phong cách sân bóng những năm 70 của chúng tôi. Trong mùa giải này, chúng tôi phát hành lại nguyên mẫu mang tính biểu tượng trong phiên bản đặc biệt Ralph Sampson 70. Phong cách đường phố cổ điển không thú vị hơn thế này.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "51.3", img = "./Images/Puma/Puma_11-Red.svg", name = "Ralph Sampson 70 Sneakers", price = "1990000", detail_heading = "Phiên bản nguyên mẫu", detail = "Quay trở lại năm 1983, khi huyền thoại bóng rổ Ralph Sampson lần đầu tiên ký hợp đồng với PUMA, anh ấy đã chơi một đôi giày nguyên mẫu dựa trên phong cách sân bóng những năm 70 của chúng tôi. Trong mùa giải này, chúng tôi phát hành lại nguyên mẫu mang tính biểu tượng trong phiên bản đặc biệt Ralph Sampson 70. Phong cách đường phố cổ điển không thú vị hơn thế này.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "52.1", img = "./Images/Puma/chim3.png", name = "Thức ăn cho thỏ trưởng thành", price = "3000000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "diff" });
            //productsList.Add(new ProductsList() { id = "52.2", img = "./Images/Puma/Puma_12-Black.svg", name = "Replicat-X Scuderia Ferrari", price = "3000000", detail_heading = "Giày Motor đỉnh cao.", detail = "Replicat-X mang dáng vẻ hung dữ và hình thức của xe đua hiện đại trong khi vẫn đúng với DNA Motorsport đích thực của PUMA. Kết hợp đế ngoài hiệu suất lấy cảm hứng từ F1 bao quanh bàn chân để tăng thêm độ bám và hỗ trợ và tấm chắn đua Scuderia Ferrari đích thực ở gót chân, Replicat-X của Ferrari mang phong cách xe đua trên đường phố.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "52.3", img = "./Images/Puma/Puma_12-Red.svg", name = "Replicat-X Scuderia Ferrari", price = "3000000", detail_heading = "Giày Motor đỉnh cao.", detail = "Replicat-X mang dáng vẻ hung dữ và hình thức của xe đua hiện đại trong khi vẫn đúng với DNA Motorsport đích thực của PUMA. Kết hợp đế ngoài hiệu suất lấy cảm hứng từ F1 bao quanh bàn chân để tăng thêm độ bám và hỗ trợ và tấm chắn đua Scuderia Ferrari đích thực ở gót chân, Replicat-X của Ferrari mang phong cách xe đua trên đường phố.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "53.1", img = "./Images/Puma/chim4.png", name = "Nước tắm cho chim 100ml", price = "2749000", detail_heading = "An toàn cho thú cưng của bạn.",type = "diff"});
            //productsList.Add(new ProductsList() { id = "53.1", img = "./Images/Puma/Puma_13-Black.svg", name = "Ferrari Future Cat", price = "2749000", detail_heading = "Tương lai của phong cách đua xe đường phố", detail = "Hai huyền thoại đua xe hợp lực - Scuderia Ferrari và Kart Cat của chính chúng tôi- để mang đến những điều tốt nhất trên thế giới. Phần trên bóng bẩy với đường khâu chi tiết và đế ngoài thấp tạo nên phong cách thực sự nổi bật trên đường phố. Thương hiệu Ferrari cho phép mọi người biết bạn thuộc đội nào.", type = "puma", color = "Đen" });
            //productsList.Add(nw eProductsList() { id = "53.2", img = "./Images/Puma/Puma_13-Red.svg", name = "Ferrari Future Cat", price = "2749000", detail_heading = "Tương lai của phong cách đua xe đường phố", detail = "Hai huyền thoại đua xe hợp lực - Scuderia Ferrari và Kart Cat của chính chúng tôi- để mang đến những điều tốt nhất trên thế giới. Phần trên bóng bẩy với đường khâu chi tiết và đế ngoài thấp tạo nên phong cách thực sự nổi bật trên đường phố. Thương hiệu Ferrari cho phép mọi người biết bạn thuộc đội nào.", type = "puma", color = "Đỏ" });
            //productsList.Add(new ProductsList() { id = "54.3", img = "./Images/Puma/Puma_14-White.svg", name = "Viz Runner Training", price = "630000", detail_heading = "Sự bổ sung mới nhất cho dòng PUMA Viz-Tech.", detail = "Phần trên được thiết kế lại lấy dấu hiệu trực tiếp từ bóng chạy trên đường phố của chúng tôi. Vỏ gót chân EVA có cấu trúc với bộ ổn định giữa bàn chân cung cấp sự hỗ trợ vượt trội qua từng bước tập luyện của bạn. TPU shank để hỗ trợ và điều khiển chuyển động. Vỏ gót chân EVA để đệm và hấp thụ sốc.", type = "puma", color = "Trắng" });
            productsList.Add(new ProductsList() { id = "54.1", img = "./Images/Puma/chim5.png", name = "Thức ăn cho vẹt", price = "630000", detail_heading = "An toàn cho thú cưng của bạn." ,type = "diff" });
            productsList.Add(new ProductsList() { id = "55.1", img = "./Images/Puma/chim6.png", name = "Sâm thái kích đá", price = "2300000", detail_heading = "An toàn cho thú cưng của bạn.",type = "diff" });
            //productsList.Add(new ProductsList() { id = "55.3", img = "./Images/Puma/Puma_15-Red.svg", name = "Scuderia Ferrari Future Kart", price = "2300000", detail_heading = "Tương lai của phong cách đua xe đường phố", detail = "Hai huyền thoại đua xe hợp lực - Scuderia Ferrari và Kart Cat của chính chúng tôi- để mang đến những điều tốt nhất trên thế giới. Phần trên bóng bẩy với đường khâu chi tiết và đế ngoài thấp tạo nên phong cách thực sự nổi bật trên đường phố. Thương hiệu Ferrari cho phép mọi người biết bạn thuộc đội nào.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "56.1", img = "./Images/Puma/chim7.png", name = "Sâu quy sống cho chim cảnh", price = "690000", detail_heading = "An toàn cho thú cưng của bạn.",type = "diff"});
            //productsList.Add(new ProductsList() { id = "56.2", img = "./Images/Puma/Puma_16-Black.svg", name = "Scuderia Ferrari Kart Cat III", price = "690000", detail_heading = "Nâng cao hiệu suất", detail = "Đôi giày Scuderia Ferrari Kart Cat này có đế giữa bằng EVA thoải mái và màu sắc đậm chất Ferrari. Gót chân của người lái được làm tròn tạo thêm vẻ ngoài đích thực cho môn đua xe thể thao và các từ 'POWER' và 'BRAKE' ở đế giày duy nhất này trong di sản đua xe thể thao của nó.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "56.3", img = "./Images/Puma/Puma_16-Red.svg", name = "Scuderia Ferrari Kart Cat III", price = "690000", detail_heading = "Nâng cao hiệu suất", detail = "Đôi giày Scuderia Ferrari Kart Cat này có đế giữa bằng EVA thoải mái và màu sắc đậm chất Ferrari. Gót chân của người lái được làm tròn tạo thêm vẻ ngoài đích thực cho môn đua xe thể thao và các từ 'POWER' và 'BRAKE' ở đế giày duy nhất này trong di sản đua xe thể thao của nó.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "57.1", img = "./Images/Puma/chim8.png", name = "Hạt kê vàng cho chim đóng gói 2kg", price = "800000", detail_heading = "An toàn cho thú cưng của bạn.", type = "diff" });
            //productsList.Add(new ProductsList() { id = "57.2", img = "./Images/Puma/Puma_17-Black.svg", name = "Electron Street Sneakers", price = "800000", detail_heading = "Tạo ra để đi trên đường phố.", detail = "Electron Street là một phong cách viztech ấn tượng nổi bật với phần đầu cắm gót chân công nghệ có thể nhìn thấy hấp thụ va chạm giúp bạn đi bộ thoải mái. Chạy trên những con phố đó thật nhanh và thoải mái với phần trên dệt kim thoáng khí, tấm quý tổng hợp để hỗ trợ và phần gót giày đàn hồi với thương hiệu đậm. Softfoam + sockliner cung cấp đệm cao cấp và sự thoải mái tối ưu cho mỗi bước đi trong ngày của bạn.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "57.3", img = "./Images/Puma/Puma_17-Red.svg", name = "Electron Street Sneakers", price = "800000", detail_heading = "Tạo ra để đi trên đường phố.", detail = "Electron Street là một phong cách viztech ấn tượng nổi bật với phần đầu cắm gót chân công nghệ có thể nhìn thấy hấp thụ va chạm giúp bạn đi bộ thoải mái. Chạy trên những con phố đó thật nhanh và thoải mái với phần trên dệt kim thoáng khí, tấm quý tổng hợp để hỗ trợ và phần gót giày đàn hồi với thương hiệu đậm. Softfoam + sockliner cung cấp đệm cao cấp và sự thoải mái tối ưu cho mỗi bước đi trong ngày của bạn.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "58.1", img = "./Images/Puma/chim9.png", name = "Cám hút mật loại 100g", price = "815000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "diff"});
            //productsList.Add(new ProductsList() { id = "58.2", img = "./Images/Puma/Puma_18-Black.svg", name = "Tazon 6 FM Sneakers", price = "815000", detail_heading = "Kiểu dáng đẹp, khác biệt với phần còn lại.", detail = "Kết nối phiên bản thứ sáu của giày thể thao lấy cảm hứng từ chạy bộ PUMA và tận hưởng cảm giác thoải mái và ổn định. Nếu các ưu tiên của bạn giống như sau: tập thể dục, ăn uống, ngủ nghỉ ... thì chúng tôi sẽ hiểu. Và bạn sẽ nhận được điều đó khi phối phiên bản mới này của đôi giày tập Tazon kiểu dáng đẹp của chúng tôi, được thiết kế để mang đến cho bạn một chuyến đi thoải mái và ổn định như những đôi giày khác.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "58.3", img = "./Images/Puma/Puma_18-Red.svg", name = "Tazon 6 FM Sneakers", price = "815000", detail_heading = "Kiểu dáng đẹp, khác biệt với phần còn lại.", detail = "Kết nối phiên bản thứ sáu của giày thể thao lấy cảm hứng từ chạy bộ PUMA và tận hưởng cảm giác thoải mái và ổn định. Nếu các ưu tiên của bạn giống như sau: tập thể dục, ăn uống, ngủ nghỉ ... thì chúng tôi sẽ hiểu. Và bạn sẽ nhận được điều đó khi phối phiên bản mới này của đôi giày tập Tazon kiểu dáng đẹp của chúng tôi, được thiết kế để mang đến cho bạn một chuyến đi thoải mái và ổn định như những đôi giày khác.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "59.1", img = "./Images/Puma/chim10.png", name = "Hạt cào cào tươi sấy lành", price = "1600000", detail_heading = "An toàn cho thú cưng của bạn.",type = "diff" });
            //productsList.Add(new ProductsList() { id = "59.2", img = "./Images/Puma/Puma_19-Black.svg", name = "GV Special Sneakers", price = "1600000", detail_heading = "Mạnh mẽ, tốc độ.", detail = "Vào cuối những năm 1970, vận động viên quần vợt người Argentina, Guillermo Vilas, đã giành được danh hiệu. Được biết đến với sự quyến rũ bằng một tay trái tay và những pha giao bóng ngoài sân cỏ, anh ấy đã kết hợp với PUMA để tạo ra một dòng giày tennis phù hợp với phong cách chiến thắng của anh ấy. Trong số đó? Giáo viên đặc biệt. Và giống như người đàn ông đứng sau huyền thoại, nó nhanh chóng đảm bảo thứ hạng của mình: Biểu tượng.", type = "puma", color = "Đen" });
            //productsList.Add(new ProductsList() { id = "59.3", img = "./Images/Puma/Puma_19-Red.svg", name = "GV Special Sneakers", price = "1600000", detail_heading = "Mạnh mẽ, tốc độ.", detail = "Vào cuối những năm 1970, vận động viên quần vợt người Argentina, Guillermo Vilas, đã giành được danh hiệu. Được biết đến với sự quyến rũ bằng một tay trái tay và những pha giao bóng ngoài sân cỏ, anh ấy đã kết hợp với PUMA để tạo ra một dòng giày tennis phù hợp với phong cách chiến thắng của anh ấy. Trong số đó? Giáo viên đặc biệt. Và giống như người đàn ông đứng sau huyền thoại, nó nhanh chóng đảm bảo thứ hạng của mình: Biểu tượng.", type = "puma", color = "Đỏ" });
            productsList.Add(new ProductsList() { id = "60.1", img = "./Images/Puma/chim11.png", name = "Cám dành cho chim chào mào", price = "1000000", detail_heading = "An toàn cho thú cưng của bạn.",  type = "diff" });
           
            Application["productsList"] = productsList;
        }

        protected void Session_Start(object sender, EventArgs e)
        {
            Session["login"] = "0";
            Session["role"] = "3";    /*0: admin; 1: khấch hàng*/
            Session["username"] = ""; /*Ten dang nhap*/
            Session["id"] = "0";      /*ID user*/

            Session["pass"] = "";
        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {

        }

        protected void Application_AuthenticateRequest(object sender, EventArgs e)
        {

        }

        protected void Application_Error(object sender, EventArgs e)
        {

        }

        protected void Session_End(object sender, EventArgs e)
        {

        }

        protected void Application_End(object sender, EventArgs e)
        {

        }
    }
}